# Use root/example as user/password credentials
version: '3.1'

services:
    node:
        build: node/.
        ports:
            - '8081:8081'
        restart: always
        volumes:
            - './node:/app'
        depends_on:
            - mongo
        links:
            - mongo
        environment:
            MONGO_USERNAME: root
            MONGO_PASSWORD: example
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

# For debug and management.
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - '8082:8082'
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example