version: '3'
services:
    node:
        build: node/.
        ports:
            - '8081:8081'
        restart: always
        depends_on:
            - mysql
        links:
            - mysql
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_USER=default_user
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=root
    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_DATABASE=default_database
                - MYSQL_USER=default_user
                - MYSQL_PASSWORD=secret
                - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./data/mysql/:/var/lib/mysql
        expose:
            - "3306"