version: '3'
services:
    node:
        build: node/.
        ports:
            - '8081:8081'
        restart: always
        depends_on:
            - db
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: database
            MYSQL_HOST: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
volumes:
    db_data:
        
